name: flutter_login
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  formz: ^0.4.0
  equatable: ^2.0.0
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  bloc: ^8.0.2
  mocktail: ^0.2.0
  bloc_test: ^9.0.2

dev_dependencies:
  test:
  mockito:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
